Exception on /api/submit [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Exception in submit: insert or update on table "submission" violates foreign key constraint "submission_teamid_fkey"
DETAIL:  Key (team_id)=(296a209e-66b9-4d38-98b5-669acb6f8419) is not present in table "team".
CONTEXT:  SQL statement "INSERT INTO SUBMISSION (team_id) VALUES (vid) RETURNING submission_id"
PL/pgSQL function submit_code_file(character varying,uuid) line 5 at SQL statement

Exception on /api/submit [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Registered team at IP 172.25.236.127
Recieved submission from f2252b84-0bc8-48de-a847-dd822925ddb2 at IP 172.25.236.127
ratelimit 1 per 1 minute (172.25.236.127) exceeded at endpoint: submit_file
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Returning get_team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Error: No data to return team_score_over_time for d1965e2c-8614-4019-a37e-b190b03abf6c
Error: No data to return submissions_stats for d1965e2c-8614-4019-a37e-b190b03abf6c
Recieved submission from d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
Recieved submission from d1965e2c-8614-4019-a37e-b190b03abf6c at IP 134.129.91.223
ratelimit 1 per 1 minute (134.129.91.223) exceeded at endpoint: submit_file
ratelimit 1 per 1 minute (134.129.91.223) exceeded at endpoint: submit_file
ratelimit 1 per 1 minute (134.129.91.223) exceeded at endpoint: submit_file
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Exception in get_leaderboard: abort() takes no keyword arguments
Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Error: No data to return for leaderboard
Exception in get_leaderboard: abort() takes no keyword arguments
Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Error: No data to return for leaderboard
Exception in get_leaderboard: abort() takes no keyword arguments
Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Error: No data to return for leaderboard
Exception in get_leaderboard: abort() takes no keyword arguments
Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Error: No data to return for leaderboard
Exception in get_leaderboard: abort() takes no keyword arguments
Exception on /api/get_leaderboard [POST]
Traceback (most recent call last):
  File "/home/acm/Documents/code/byte_le_royale_2021/server/Server.py", line 131, in get_leaderboard
    abort(500, description="No data to return for leaderboard yet")
TypeError: abort() takes no keyword arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/acm/Documents/code/byte_le_royale_2021/server/Server.py", line 131, in get_leaderboard
    abort(500, description="No data to return for leaderboard yet")
TypeError: abort() takes no keyword arguments
Error: No data to return for leaderboard
Error: No data to return for leaderboard
Exception in get_leaderboard: 500 Internal Server Error: No data to return for leaderboard yet
